# (namn, vinted-sökord, vinted-märken, kategori, tradera-sökord)
K = [
 ("RL kabelstickat", "kabelstickad", ["Ralph Lauren", "Polo Ralph Lauren"], "klader", "ralph lauren kabelstickad"),
 ("RL quarter/half zip", "half zip", ["Ralph Lauren", "Polo Ralph Lauren"], "klader", "ralph lauren half zip"),
 ("RL skjorta", "skjorta", ["Ralph Lauren", "Polo Ralph Lauren"], "klader", "ralph lauren skjorta herr"),
 ("RL Harrington", "harrington", ["Ralph Lauren", "Polo Ralph Lauren"], "klader", "ralph lauren harrington"),
 ("RL dunjacka", "dunjacka", ["Ralph Lauren", "Polo Ralph Lauren"], "klader", "ralph lauren dunjacka"),
 ("RL kashmir", "cashmere", ["Ralph Lauren", "Polo Ralph Lauren"], "klader", "ralph lauren cashmere"),
 ("RL rugby", "rugby", ["Ralph Lauren", "Polo Ralph Lauren"], "klader", "ralph lauren rugby"),
 ("Barbour vaxjacka", "vaxjacka", ["Barbour"], "klader", "barbour vaxjacka"),
 ("Barbour Bedale/Beaufort", "bedale", ["Barbour"], "klader", "barbour bedale"),
 ("Stone Island alla", "", ["Stone Island"], "klader", "stone island"),
 ("CP Company alla", "", ["C.P. Company"], "klader", "cp company"),
 ("Our Legacy alla", "", ["Our Legacy"], "klader", "our legacy"),
 ("Acne Studios herr", "", ["Acne Studios"], "klader", "acne studios herr"),
 ("Arc'teryx jacka", "jacka", ["Arc'teryx"], "klader", "arcteryx jacka"),
 ("Arc'teryx alla", "", ["Arc'teryx"], "klader", "arcteryx"),
 ("Patagonia fleece", "fleece", ["Patagonia"], "klader", "patagonia fleece"),
 ("TNF Nuptse", "nuptse", ["The North Face"], "klader", "north face nuptse"),
 ("Moncler dunjacka", "", ["Moncler"], "klader", "moncler jacka herr"),
 ("Canada Goose", "", ["Canada Goose"], "klader", "canada goose herr"),
 ("Carhartt Detroit/Active", "detroit", ["Carhartt", "Carhartt WIP"], "klader", "carhartt detroit"),
 ("Carhartt jacka", "jacka", ["Carhartt", "Carhartt WIP"], "klader", "carhartt jacka"),
 ("Fjällräven Greenland", "greenland", ["Fjällräven"], "klader", "fjällräven greenland"),
 ("Fjällräven byxor Keb/Vidda", "byxor", ["Fjällräven"], "klader", "fjällräven keb byxor"),
 ("Fjällräven Kånken", "kånken", ["Fjällräven"], "", "kånken"),
 ("Haglöfs jacka", "jacka", ["Haglöfs"], "klader", "haglöfs jacka herr"),
 ("Peak Performance jacka", "jacka", ["Peak Performance"], "klader", "peak performance jacka herr"),
 ("Houdini", "", ["Houdini"], "klader", "houdini power houdi"),
 ("Woolpower", "", ["Woolpower"], "klader", "woolpower"),
 ("Stenströms skjorta", "skjorta", ["Stenströms"], "klader", "stenströms skjorta"),
 ("Eton skjorta", "skjorta", ["Eton"], "klader", "eton skjorta"),
 ("Oscar Jacobson kavaj", "kavaj", ["Oscar Jacobson"], "klader", "oscar jacobson kavaj"),
 ("Tiger of Sweden kavaj", "kavaj", ["Tiger of Sweden"], "klader", "tiger of sweden kavaj"),
 ("Morris", "", ["Morris"], "klader", "morris herr"),
 ("Gant", "", ["Gant"], "klader", "gant herr"),
 ("Lacoste", "", ["Lacoste"], "klader", "lacoste herr"),
 ("Levi's 501", "501", ["Levi's"], "klader", "levis 501"),
 ("Nudie jeans", "", ["Nudie Jeans"], "klader", "nudie jeans"),
 ("Loro Piana", "", ["Loro Piana"], "klader", "loro piana"),
 ("Brunello Cucinelli", "", ["Brunello Cucinelli"], "klader", "brunello cucinelli"),
 ("Herno", "", ["Herno"], "klader", "herno"),
 ("Kashmir tröja (alla märken)", "kashmir", [], "klader", "kashmir tröja herr"),
 ("Hermès slips", "slips", ["Hermès"], "accessoarer", "hermes slips"),
 ("Hestra handskar", "", ["Hestra"], "accessoarer", "hestra"),
 ("LV plånbok", "plånbok", ["Louis Vuitton"], "accessoarer", "louis vuitton plånbok"),
 ("New Balance 990-serien", "990", ["New Balance"], "skor", "new balance 990"),
 ("New Balance 2002R/1906", "2002r", ["New Balance"], "skor", "new balance 2002r"),
 ("Salomon XT-6", "xt-6", ["Salomon"], "skor", "salomon xt-6"),
 ("Asics Gel", "gel", ["ASICS"], "skor", "asics gel kayano"),
 ("Paraboot", "", ["Paraboot"], "skor", "paraboot"),
 ("Church's", "", ["Church's"], "skor", "church's skor"),
 ("Red Wing", "", ["Red Wing"], "skor", "red wing"),
 ("Dr. Martens", "", ["Dr. Martens"], "skor", "dr martens"),
 ("Common Projects", "", ["Common Projects"], "skor", "common projects"),
 ("Birkenstock Boston", "boston", ["Birkenstock"], "skor", "birkenstock boston"),
 # Felstavningar och fynd-ord, utan märkesfilter
 ("Felstavat: ralf lauren", "ralf lauren", [], "", "ralf lauren"),
 ("Felstavat: stone iland", "stone iland", [], "", "stone iland"),
 ("Felstavat: barbor", "barbor", [], "", "barbor"),
 ("Felstavat: monkler/moncleer", "monkler", [], "", "monkler"),
 ("Felstavat: arcteryx", "arcteryx", [], "", "arcteryx"),
 ("Fyndord: vaxjacka (utan märke)", "vaxjacka", [], "klader", "vaxjacka"),
 ("Fyndord: pappas/farfars", "pappas", [], "klader", "pappas"),
 ("Fyndord: dödsbo", "dödsbo", [], "", "dödsbo kläder"),
]
